spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.mandatory-file-encoding=UTF-8
company.name=\u306b\u307b\u3093\u3054\u30c6\u30b9\u30c8 Kaisha Test
company.address=Tokyo, Shinjuku 1-2-3
company.phone=03-0000-0000
company.email=info@example.com